# --- Main Colors ---
background            #171216
foreground            #ebdfe6
cursor                #ebdfe6
cursor_text_color     #171216

selection_background  #534152
selection_foreground  #f5dbf0

url_color             #f6b8ab

# --- ANSI Colors ---
color0                #171216
color1                #ffb4ab
color2                #f6b8ab
color3                #d8bfd4
color4                #edb4eb
color5                #f6b8ab
color6                #d8bfd4
color7                #ebdfe6

color8                #4d444c
color9                #93000a
color10               #673b32
color11               #534152
color12               #633664
color13               #534152
color14               #673b32
color15               #d0c3cc

# --- Starship Prompt Bubbles ---
color255              #633664
color254              #edb4eb
color253              #534152
color252              #d8bfd4
color251              #673b32
color250              #f6b8ab
color249              #93000a
color248              #ffb4ab

color232              #ffd6fb
color233              #4a204c
color234              #f5dbf0
color235              #3c2b3b
color236              #ffdad3
color237              #4c261e
color238              #ffdad6
color239              #690005
color240              #ffd6fb

# Matched with unthemed light/dark
color243              #edb4eb
color244              #ffb4ab
color245              #4d444c

# --- UI Elements ---
active_tab_foreground   #4a204c
active_tab_background   #edb4eb
inactive_tab_foreground #ffd6fb
inactive_tab_background #633664

active_border_color     #edb4eb
inactive_border_color   #998d96

# --- Marks ---
mark1_foreground        #320936
mark1_background        #ffd6fb
mark2_foreground        #261625
mark2_background        #f5dbf0
mark3_foreground        #33110b
mark3_background        #ffdad3
