# --- Main Colors ---
background            #16130b
foreground            #e9e2d4
cursor                #e9e2d4
cursor_text_color     #16130b

selection_background  #4f462a
selection_foreground  #efe2bb

url_color             #abd0b1

# --- ANSI Colors ---
color0                #16130b
color1                #ffb4ab
color2                #abd0b1
color3                #d3c6a1
color4                #dec56e
color5                #abd0b1
color6                #d3c6a1
color7                #e9e2d4

color8                #4b4639
color9                #93000a
color10               #2d4e36
color11               #4f462a
color12               #554500
color13               #4f462a
color14               #2d4e36
color15               #cec6b4

# --- Starship Prompt Bubbles ---
color255              #554500
color254              #dec56e
color253              #4f462a
color252              #d3c6a1
color251              #2d4e36
color250              #abd0b1
color249              #93000a
color248              #ffb4ab

color232              #fbe186
color233              #3b2f00
color234              #efe2bb
color235              #373016
color236              #c6eccc
color237              #163721
color238              #ffdad6
color239              #690005
color240              #fbe186

# Matched with unthemed light/dark
color243              #dec56e
color244              #ffb4ab
color245              #4b4639

# --- UI Elements ---
active_tab_foreground   #3b2f00
active_tab_background   #dec56e
inactive_tab_foreground #fbe186
inactive_tab_background #554500

active_border_color     #dec56e
inactive_border_color   #979080

# --- Marks ---
mark1_foreground        #221b00
mark1_background        #fbe186
mark2_foreground        #211b04
mark2_background        #efe2bb
mark3_foreground        #00210e
mark3_background        #c6eccc
