# --- Main Colors ---
background            #121318
foreground            #e3e1e9
cursor                #e3e1e9
cursor_text_color     #121318

selection_background  #424659
selection_foreground  #dee1f9

url_color             #e4bad9

# --- ANSI Colors ---
color0                #121318
color1                #ffb4ab
color2                #e4bad9
color3                #c2c5dd
color4                #b8c4ff
color5                #e4bad9
color6                #c2c5dd
color7                #e3e1e9

color8                #45464f
color9                #93000a
color10               #5c3d56
color11               #424659
color12               #364379
color13               #424659
color14               #5c3d56
color15               #c6c5d0

# --- Starship Prompt Bubbles ---
color255              #364379
color254              #b8c4ff
color253              #424659
color252              #c2c5dd
color251              #5c3d56
color250              #e4bad9
color249              #93000a
color248              #ffb4ab

color232              #dde1ff
color233              #1f2d61
color234              #dee1f9
color235              #2c2f42
color236              #ffd7f4
color237              #43273f
color238              #ffdad6
color239              #690005
color240              #dde1ff

# Matched with unthemed light/dark
color243              #b8c4ff
color244              #ffb4ab
color245              #45464f

# --- UI Elements ---
active_tab_foreground   #1f2d61
active_tab_background   #b8c4ff
inactive_tab_foreground #dde1ff
inactive_tab_background #364379

active_border_color     #b8c4ff
inactive_border_color   #90909a

# --- Marks ---
mark1_foreground        #06164b
mark1_background        #dde1ff
mark2_foreground        #171b2c
mark2_background        #dee1f9
mark3_foreground        #2c1229
mark3_background        #ffd7f4
