[config]
version_check = true
fallback_color = "#ffffff"
prefer = "value"
caching = false
command = "awww img --transition-type center {{ image }}"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wofi]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.waypaper]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waypaper/colors.css'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi_theme.toml'
output_path = '~/.config/yazi/theme.toml'

# VS Code matugen extension
[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.quickshell]
input_path = './templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

